# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5dee5b6e89d2e8d2ad7fde6477d75115cfe17967c2d43652e669b7076e89bf097756476f16b2aa24fe59287431baa6403e22fe4e18f8ebf3d86c5a7389d9bd4

test:
  secret_key_base: 01bb7b42a93ba9dc8552127ebb735e8253d5aabb29d6470c7dce72d479a4d67abb486875c7ea906b4feb83ff7f9bee0e654489c8247e55363066a081089b5611

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
